### ISSUE TITLE
Fresh fedora image on docker

### ISSUE THREAD

**Issue by IvanTurgenev** [decathorpe/kentauros#1]
[ddd@5db5d2120268 kentauros]$ ./ktr.py construct --all

ktr: Packages:
     - desktop-file-utils
     - desktop-file-utils-git
     - granite
     - granite-bzr
     - granite-bzr-0.4
     - mesa
     - mesa-git
     - mesa-git-12.0

ktr: ------------------------------------------------
ktr: Executing actions on package: desktop-file-utils
ktr: ------------------------------------------------
Traceback (most recent call last):
  File "./ktr.py", line 21, in <module>
    sys.exit(run())
  File "/home/ddd/kentauros/kentauros/run.py", line 315, in run
    actions_success, actions_failure = do_process_packages()
  File "/home/ddd/kentauros/kentauros/run.py", line 266, in do_process_packages
    success = action.execute()
  File "/home/ddd/kentauros/kentauros/actions/construct.py", line 39, in execute
    success = constructor.execute()
  File "/home/ddd/kentauros/kentauros/modules/constructor/srpm.py", line 686, in execute
    success = self.prepare()
  File "/home/ddd/kentauros/kentauros/modules/constructor/srpm.py", line 627, in prepare
    success = self._copy_specs_around()
  File "/home/ddd/kentauros/kentauros/modules/constructor/srpm.py", line 533, in _copy_specs_around
    spec = RPMSpec(self.path, self.source)
  File "/home/ddd/kentauros/kentauros/modules/constructor/rpm/__init__.py", line 86, in __init__
    self.contents = file.read()
  File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3608: ordinal not in range(128)

**Comment by decathorpe** [comment]
what are you trying to do?

**Comment by IvanTurgenev** [comment]
run the examples

found the error on

 File "/home/ddd/kentauros/kentauros/modules/constructor/rpm/__init__.py", line 86, in __init__

`self.path = path
        self.source = source
        print(path)
        with open(path, "r") as file:
            self.contents = file.read()
`
putted a print showne problem on *.spec
fixed it by going to position
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3608: ordinal not in range(128)
there were some problematic names like Skytt, Dan Hor

the next command fixes it but you have to search at each position for a part of the string to put on sed so it can delete the line and the one after it

find examples/specs/ -type f -name '*.spec' | xargs sed  -i -e '/Dan Hor/ { N; d; }'

**Comment by decathorpe** [comment]
I don't know what's happening here, because I don't get an exception when running the command you're running above.

Is it possible you're running python3 under a non-UTF-8 locale?

**Comment by IvanTurgenev** [comment]
locale 

LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by IvanTurgenev** [comment]
now this

[ddd@5db5d2120268 kentauros]$ ./ktr.py construct --all

ktr: Packages:
     - desktop-file-utils
     - desktop-file-utils-git
     - granite
     - granite-bzr
     - granite-bzr-0.4
     - mesa
     - mesa-git
     - mesa-git-12.0

ktr: ------------------------------------------------
ktr: Executing actions on package: desktop-file-utils
ktr: ------------------------------------------------
ktr/constructor/srpm: rpmbuild command:
                    : rpmbuild --quiet -bs /tmp/tmp4gzwpdk0/rpmbuild/SPECS/desktop-file-utils.spec 
error: File /tmp/tmp4gzwpdk0/rpmbuild/SOURCES/desktop-file-utils-0.23.tar.xz: No such file or directory
ktr/actions: desktop-file-utils: Success!

ktr: ----------------------------------------------------
ktr: Executing actions on package: desktop-file-utils-git
ktr: ----------------------------------------------------
Traceback (most recent call last):
  File "./ktr.py", line 21, in <module>
    sys.exit(run())
  File "/home/ddd/kentauros/run.py", line 315, in run
    actions_success, actions_failure = do_process_packages()
  File "/home/ddd/kentauros/kentauros/run.py", line 266, in do_process_packages
    success = action.execute()
  File "/home/ddd/kentauros/kentauros/actions/construct.py", line 39, in execute
    success = constructor.execute()
  File "/home/ddd/kentauros/kentauros/modules/constructor/srpm.py", line 686, in execute
    success = self.prepare()
  File "/home/ddd/kentauros/kentauros/modules/constructor/srpm.py", line 620, in prepare
    self._cleanup_sources()
  File "/home/ddd/kentauros/kentauros/modules/constructor/srpm.py", line 317, in _cleanup_sources
    if os.path.isfile(tarballs[0]):
IndexError: list index out of range

**Comment by decathorpe** [comment]
Then why is python3 then using the "ascii" decoder?

Also, the second exception shouldn't happen - but:
You need to download the package sources before running the constructor.

**Comment by IvanTurgenev** [comment]
yeah found soemthing on python

Python 2.7.13 (default, May 10 2017, 20:04:28) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale() 
(None, None)
>>>

**Comment by IvanTurgenev** [comment]
where do i put the sources of the files?

**Comment by decathorpe** [comment]
Is python3 giving the same output?

**Comment by decathorpe** [comment]
Run `./ktr.py prepare --all` to download source files for all projects.

**Comment by IvanTurgenev** [comment]
Is python3 giving the same output?

that the ouput of the REPL

**Comment by decathorpe** [comment]
The output from your comment above is from a python2 environment (Python 2.7.13).

**Comment by IvanTurgenev** [comment]
ups yes

Python 3.5.3 (default, Mar 21 2017, 17:21:33) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale() 
(None, None)
>>>

**Comment by decathorpe** [comment]
That explains the unicode error ... does running `export LC_ALL=en_US.UTF-8` fix the problem?

**Comment by IvanTurgenev** [comment]
wait will test

meawhile getting this

ktr: -------------------------------------------
ktr: Executing actions on package: mesa-git-12.0
ktr: -------------------------------------------
ktr/builder/mock: Specified chroots:
                  - fedora-24-x86_64
ktr/builder/mock: /usr/bin/mock command:
                : /usr/bin/mock --quiet -r fedora-24-x86_64 /home/ddd/kentauros/examples/packages/mesa-git-12.0/mesa-12.0.3+git170124.020520.13953f01-1.fc25.src.rpm 
ERROR: Namespace unshare failed.
ERROR: It seems we are running inside of Docker. Let skip unsharing.
ERROR: You should *not* run anything but Mock in this container. You have been warned!
ERROR: Exception(/home/ddd/kentauros/examples/packages/mesa-git-12.0/mesa-12.0.3+git170124.020520.13953f01-1.fc25.src.rpm) Config(fedora-24-x86_64) 0 minutes 0 seconds
ERROR: Command failed. See logs for output.
 # /bin/mount -n -t proc proc /var/lib/mock/fedora-24-x86_64/root/proc
ktr/builder/mock: Build failures:
                  - ('/home/ddd/kentauros/examples/packages/mesa-git-12.0/mesa-12.0.3+git170124.020520.13953f01-1.fc25.src.rpm', 'fedora-24-x86_64')
ktr/builder/mock: Binary package building unsuccessful, aborting action.
ktr/actions: mesa-git-12.0: Not successful.

**Comment by IvanTurgenev** [comment]
yes export LC_ALL=en_US.UTF-8 seems to fix it

**Comment by decathorpe** [comment]
Yeah I suspect running mock inside a docker container might cause issues ... have you used mock inside docker successfully before?

**Comment by IvanTurgenev** [comment]
first timer on almost all

**Comment by IvanTurgenev** [comment]
looking around --cap-add=SYS_ADMIN pops up

docker run -ti --cap-add=SYS_ADMIN -v /home/ddd/docker:/home fedora:latest bash

will try

**Comment by IvanTurgenev** [comment]
will not wanted to build syncthing to arm i see is not possible...
i will try to convert the arch ARM syncthing pkg to rpm

**Comment by decathorpe** [comment]
You can use my syncthing source RPM package for building on a raspberry pi:
<https://copr-be.cloud.fedoraproject.org/results/decathorpe/syncthing/fedora-25-x86_64/00552646-syncthing/syncthing-0.14.28-1.fc25.src.rpm>
Just execute `mock $FILE` on your RPi fedora installation and it will build ARM packages of syncthing.

**Comment by IvanTurgenev** [comment]
can i crosscompile on my pc?

**Comment by decathorpe** [comment]
You'll need to run it in an arm VM on qemu.
I think running it on the raspberry pi directly is the least complicated solution.

**Comment by IvanTurgenev** [comment]
mock pulls a lot of dependencies i dont wanna fill it up or install unnecessary packages

**Comment by decathorpe** [comment]
Which version of fedora are you using?

**Comment by IvanTurgenev** [comment]
both rasp b2 and pc fedora 25

**Comment by decathorpe** [comment]
I'll try building a package on the fedora infrastructure.

**Comment by IvanTurgenev** [comment]
thanks

**Comment by decathorpe** [comment]
You can get a syncthing package for arm from
https://koji.fedoraproject.org/koji/taskinfo?taskID=19629998
now.

**Comment by IvanTurgenev** [comment]
thank you man
is Syncthing-inotify included? or it needs to also installed

**Comment by decathorpe** [comment]
It's not included, and I can't build it the same way I just built syncthing since there's no syncthing package for fedora yet.

**Comment by IvanTurgenev** [comment]
ok nevermind, i appreciate thanks
